# Generated by Django 5.2.14 on 2026-05-14 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_member_email_verification'),
        ('revenues', '0009_backfill_revenue_is_initial_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('received_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Recebido')),
                ('date', models.DateField(verbose_name='Data de Registro')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('category', models.CharField(choices=[('deposit', 'Depósito'), ('award', 'Prêmio'), ('salary', 'Salário'), ('ticket', 'Vale'), ('income', 'Rendimentos'), ('refund', 'Reembolso'), ('cashback', 'Cashback'), ('transfer', 'Transferência Recebida'), ('received_loan', 'Empréstimo Recebido'), ('loan_devolution', 'Devolução de empréstimo')], max_length=200, verbose_name='Categoria')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('received', 'Recebido'), ('overdue', 'Em atraso'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member', verbose_name='Devedor (Membro)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Valor a Receber',
                'verbose_name_plural': 'Valores a Receber',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('received', models.BooleanField(default=False, verbose_name='Recebido')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('receipt_revenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_installment_receipts', to='revenues.revenue', verbose_name='Receita de Recebimento')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='receivables.receivable', verbose_name='Valor a Receber')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Parcela de Valor a Receber',
                'verbose_name_plural': 'Parcelas de Valores a Receber',
                'ordering': ['receivable', 'installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['-date'], name='receivables_date_be9711_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['status', '-date'], name='receivables_status_8d2090_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['category', '-date'], name='receivables_categor_539678_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableinstallment',
            index=models.Index(fields=['receivable', 'received'], name='receivables_receiva_9e05da_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableinstallment',
            index=models.Index(fields=['due_date'], name='receivables_due_dat_47ea11_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivableinstallment',
            constraint=models.UniqueConstraint(fields=('receivable', 'installment_number'), name='unique_receivable_installment_number'),
        ),
    ]
