# Generated by Django 5.2.13 on 2026-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_planning', '0010_alter_routinetask_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, help_text='Data limite para concluir o objetivo', null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='routinetask',
            name='allowed_skips_per_month',
            field=models.PositiveIntegerField(default=0, help_text='Quantas faltas são toleradas por mês sem quebrar o streak (0 = nenhuma tolerância)', verbose_name='Faltas Permitidas por Mês'),
        ),
        migrations.AddField(
            model_name='routinetask',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Prioridade'),
        ),
    ]
