# Generated by Django 5.2.13 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_planning', '0011_add_priority_deadline_skips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinetask',
            name='allowed_skips_per_month',
            field=models.PositiveIntegerField(default=0, help_text='Quantas faltas por mes sem quebrar o streak (0 = sem tolerancia)', verbose_name='Faltas Permitidas por Mês'),
        ),
    ]
