# Generated by Django 5.2.14 on 2026-05-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_planning', '0021_add_exercise_catalog_and_workout_exercise_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='Medal', max_length=50, verbose_name='Ícone'),
        ),
    ]
