# Generated by Django 5.2.14 on 2026-06-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_planning', '0025_workoutday_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_source',
            field=models.CharField(choices=[('task_instances', 'Instâncias de Tarefas'), ('workout_sessions', 'Sessões de Treino'), ('meal_logs', 'Registros de Refeição'), ('custom', 'Manual')], default='task_instances', help_text='Define de onde vem o progresso automático: tarefas, treinos, refeições ou manual', max_length=20, verbose_name='Fonte do Progresso'),
        ),
    ]
