# Generated by Django 5.2.15 on 2026-06-10 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_email_verification'),
        ('personal_planning', '0026_goal_source_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoutineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone do Lucide (ex: Heart, BookOpen, Dumbbell)', max_length=50, null=True, verbose_name='Ícone')),
                ('tasks', models.JSONField(default=list, help_text='Lista de tarefas no mesmo formato do RoutineTemplateImportView', verbose_name='Tarefas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_templates', to='members.member', verbose_name='Dono')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Rotina do Usuário',
                'verbose_name_plural': 'Templates de Rotina do Usuário',
                'ordering': ['-created_at'],
            },
        ),
    ]
