# Generated by Django 5.2.15 on 2026-06-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_planning', '0030_add_height_neck_to_bodymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='met_value',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Equivalente Metabólico da Tarefa. Usado para estimar calorias gastas: kcal = MET × peso_kg × horas.', max_digits=4, verbose_name='MET'),
        ),
    ]
