apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mindledger-staging
  labels:
    app.kubernetes.io/name: mindledger
    app.kubernetes.io/component: frontend
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
