# Generated by Django 5.2.15 on 2026-06-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentário (sem exercício ou muito leve)'), ('lightly_active', 'Levemente Ativo (exercício 1–3 dias/semana)'), ('moderately_active', 'Moderadamente Ativo (exercício 3–5 dias/semana)'), ('very_active', 'Muito Ativo (exercício intenso 6–7 dias/semana)'), ('extremely_active', 'Extremamente Ativo (trabalho físico + exercício intenso)')], default='sedentary', help_text='Usado para cálculo do gasto calórico diário total (TDEE).', max_length=20, verbose_name='Nível de Atividade'),
        ),
    ]
