# Generated by Django 5.2.13 on 2026-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_planning', '0013_add_closing_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routinetask',
            options={'ordering': ['default_time', 'category', 'name'], 'verbose_name': 'Tarefa Rotineira', 'verbose_name_plural': 'Tarefas Rotineiras'},
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='unit',
            field=models.CharField(choices=[('vez', 'vez'), ('minuto', 'minuto'), ('hora', 'hora'), ('ml', 'ml'), ('copo', 'copo'), ('litro', 'litro'), ('página', 'página'), ('km', 'km'), ('metro', 'metro'), ('passo', 'passo'), ('repetição', 'repetição'), ('série', 'série'), ('capítulo', 'capítulo'), ('exercício', 'exercício'), ('dose', 'dose'), ('comprimido', 'comprimido')], default='vez', max_length=50, verbose_name='Unidade'),
        ),
    ]
