# Generated by Django 5.2.14 on 2026-05-22 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_email_verification'),
        ('personal_planning', '0020_add_workout_and_nutrition_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='load',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Carga'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='load_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('bw', 'Peso corporal')], default='kg', max_length=10, verbose_name='Unidade de Carga'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='name',
            field=models.CharField(help_text='Preenchido automaticamente a partir do catálogo.', max_length=200, verbose_name='Nome do Exercício'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('muscle_groups', models.CharField(blank=True, help_text='Ex: Peitoral / Tríceps', max_length=200, null=True, verbose_name='Grupos Musculares')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises_catalog', to='members.member', verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_exercises', to='personal_planning.exercise', verbose_name='Exercício do Catálogo'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['owner', 'name'], name='personal_pl_owner_i_fcbff6_idx'),
        ),
    ]
