# Generated by Django 5.2.15 on 2026-06-15 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_planning", "0028_challenge_bodymetric_chained_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bodymetric",
            new_name="personal_pl_owner_i_4050d6_idx",
            old_name="bodymetric_owner_date_idx",
        ),
        migrations.RenameIndex(
            model_name="challenge",
            new_name="personal_pl_owner_i_56e594_idx",
            old_name="challenge_owner_status_idx",
        ),
        migrations.RenameIndex(
            model_name="challenge",
            new_name="personal_pl_start_d_24dea0_idx",
            old_name="challenge_dates_idx",
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Excluído por",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizado por",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Excluído por",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="bodymetric",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Criado em"
            ),
        ),
        migrations.AlterField(
            model_name="bodymetric",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Excluído em"
            ),
        ),
        migrations.AlterField(
            model_name="bodymetric",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="bodymetric",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Excluído"),
        ),
        migrations.AlterField(
            model_name="bodymetric",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Atualizado em"
            ),
        ),
        migrations.AlterField(
            model_name="bodymetric",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Criado em"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Excluído em"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Excluído"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="template_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Tarefa rotineira que serve de base para o desafio",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenges",
                to="personal_planning.routinetask",
                verbose_name="Tarefa de Referência",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Atualizado em"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
