# Generated by Django 5.2.15 on 2026-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_planning', '0029_rename_bodymetric_owner_date_idx_personal_pl_owner_i_4050d6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymetric',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='bodymetric',
            name='neck_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pescoço (cm)'),
        ),
        migrations.AlterField(
            model_name='bodymetric',
            name='body_fat_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gordura Corporal (%) — calculado pelo método da Marinha'),
        ),
    ]
