# Generated by Django 5.2.16 on 2026-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_planning", "0033_add_wellness_center_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymetric",
            name="abdomen_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Abdômen (cm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="arm_left_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Braço Esquerdo (cm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="arm_right_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Braço Direito (cm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="body_fat_method",
            field=models.CharField(
                blank=True,
                choices=[("navy", "Marinha"), ("pollock", "Pollock 7 Dobras")],
                max_length=10,
                null=True,
                verbose_name="Método de Cálculo da Gordura Corporal",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="calf_left_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Perna Esquerda (cm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="calf_right_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Perna Direita (cm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="chest_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Tórax (cm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="shoulders_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Ombros (cm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="skinfold_abdominal_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Dobra Abdominal (mm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="skinfold_chest_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Dobra Peitoral (mm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="skinfold_midaxillary_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Dobra Axilar Média (mm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="skinfold_subscapular_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Dobra Subescapular (mm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="skinfold_suprailiac_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Dobra Supra-Ilíaca (mm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="skinfold_thigh_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Dobra Coxa (mm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="skinfold_triceps_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Dobra Tricipital (mm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="thigh_left_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Coxa Esquerda (cm)",
            ),
        ),
        migrations.AddField(
            model_name="bodymetric",
            name="thigh_right_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Coxa Direita (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymetric",
            name="body_fat_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Gordura Corporal (%)",
            ),
        ),
    ]
