# Generated by Django 6.0.7 on 2026-08-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_planning",
            "0034_bodymetric_abdomen_cm_bodymetric_arm_left_cm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutday",
            name="default_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Usada junto com o horário de início padrão para pré-preencher o término da sessão.",
                null=True,
                verbose_name="Duração Padrão (minutos)",
            ),
        ),
        migrations.AddField(
            model_name="workoutday",
            name="default_start_time",
            field=models.TimeField(
                blank=True,
                help_text="Horário usado para pré-preencher o início ao registrar uma sessão desta divisão.",
                null=True,
                verbose_name="Horário de Início Padrão",
            ),
        ),
        migrations.AddField(
            model_name="workoutsessionexercise",
            name="load_target",
            field=models.CharField(
                blank=True,
                help_text="Snapshot da carga planejada, usada para pré-preencher as séries.",
                max_length=20,
                null=True,
                verbose_name="Carga Alvo",
            ),
        ),
        migrations.AddField(
            model_name="workoutsessionexercise",
            name="load_target_unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("lb", "lb"), ("bw", "Peso corporal")],
                default="kg",
                max_length=10,
                verbose_name="Unidade da Carga Alvo",
            ),
        ),
    ]
