# Generated by Django 6.0.8 on 2026-09-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_planning",
            "0039_routinetask_is_optional_taskinstance_is_optional",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodymetric",
            options={
                "ordering": ["-measured_at", "-created_at"],
                "verbose_name": "Métrica Corporal",
                "verbose_name_plural": "Métricas Corporais",
            },
        ),
    ]
