# Generated by Django 6.0.8 on 2026-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_planning",
            "0041_focusblock_focusblocktask_focusblock_tasks_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="focusblock",
            name="weekdays",
            field=models.JSONField(
                default=list,
                help_text="Dias em que o bloco aparece no Checklist Diário [0-6, 0=Segunda] (mesma convenção de RoutineTask.custom_weekdays)",
                verbose_name="Dias da Semana",
            ),
        ),
    ]
