# Generated by Django 6.0.8 on 2026-09-28 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_member_activity_level"),
        ("personal_planning", "0042_focusblock_weekdays"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meallog",
            name="task_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Preenchido quando o registro veio da conclusão da tarefa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_logs",
                to="personal_planning.taskinstance",
                verbose_name="Tarefa de Origem",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="linked_meal_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Concluir a tarefa registra a refeição e vice-versa (só categoria Nutrição)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_routine_tasks",
                to="personal_planning.mealtype",
                verbose_name="Refeição Vinculada",
            ),
        ),
        migrations.CreateModel(
            name="HydrationGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Excluído"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "daily_target_ml",
                    models.PositiveIntegerField(
                        verbose_name="Meta Diária (ml)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydration_goal",
                        to="members.member",
                        verbose_name="Proprietário",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta de Hidratação",
                "verbose_name_plural": "Metas de Hidratação",
            },
        ),
        migrations.AddField(
            model_name="routinetask",
            name="linked_hydration_goal",
            field=models.ForeignKey(
                blank=True,
                help_text="Cada ocorrência concluída registra meta ÷ ocorrências do dia (só categoria Nutrição)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_routine_tasks",
                to="personal_planning.hydrationgoal",
                verbose_name="Meta de Hidratação Vinculada",
            ),
        ),
        migrations.CreateModel(
            name="WaterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Excluído"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário"
                    ),
                ),
                (
                    "amount_ml",
                    models.PositiveIntegerField(
                        verbose_name="Quantidade (ml)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_logs",
                        to="members.member",
                        verbose_name="Proprietário",
                    ),
                ),
                (
                    "task_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido quando o registro veio da conclusão da tarefa",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="water_logs",
                        to="personal_planning.taskinstance",
                        verbose_name="Tarefa de Origem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Água",
                "verbose_name_plural": "Registros de Água",
                "ordering": ["-date", "-time"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-date"],
                        name="personal_pl_owner_i_abeb01_idx",
                    )
                ],
            },
        ),
    ]
