# Generated by Django 6.0.8 on 2026-09-28 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0029_alter_flashcard_created_at_and_more"),
        ("members", "0007_member_activity_level"),
        ("personal_planning", "0043_hydration_goal_water_log"),
        ("vaults", "0015_vault_yield_tax_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mealtype",
            name="default_menu_option",
            field=models.ForeignKey(
                blank=True,
                help_text="Usada ao registrar a refeição pela tarefa vinculada; sem ela, vale a opção de maior caloria",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="personal_planning.menuoption",
                verbose_name="Opção Padrão",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinetask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("linked_meal_type__isnull", False),
                ),
                fields=("linked_meal_type",),
                name="unique_active_task_per_meal_type",
            ),
        ),
    ]
