# Generated by Django 6.0.8 on 2026-09-28 14:26

from django.db import migrations, models


def copy_day_of_week(apps, schema_editor):
    WorkoutDay = apps.get_model("personal_planning", "WorkoutDay")
    for day in WorkoutDay.objects.filter(day_of_week__isnull=False):
        day.days_of_week = [day.day_of_week]
        day.save(update_fields=["days_of_week"])


class Migration(migrations.Migration):

    dependencies = [
        ("personal_planning", "0044_meal_task_one_to_one_default_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                choices=[
                    ("cardio", "Cardiovascular"),
                    ("resistance", "Resistência"),
                    ("mobility", "Mobilidade"),
                ],
                default="resistance",
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="linked_workout",
            field=models.BooleanField(
                default=False,
                help_text="Aparece só em dias com treino agendado e é concluída apenas pelo registro das sessões (só categoria Exercício)",
                verbose_name="Vinculada ao Treino",
            ),
        ),
        migrations.AddField(
            model_name="workoutday",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Dias da semana em que esta divisão é executada (0=Seg, 6=Dom). Vazio = qualquer dia.",
                verbose_name="Dias da Semana",
            ),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="set_targets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Carga/repetições de cada série: [{"reps": 12, "load": "20"}]. Valores vazios usam reps_min/load.',
                verbose_name="Alvos por Série",
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="category",
            field=models.CharField(
                choices=[
                    ("cardio", "Cardiovascular"),
                    ("resistance", "Resistência"),
                    ("mobility", "Mobilidade"),
                ],
                default="resistance",
                help_text="Exercícios do plano devem ser da mesma categoria",
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
        migrations.RunPython(copy_day_of_week, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="workoutday",
            name="day_of_week",
        ),
    ]
