# Generated by Django 6.0.8 on 2026-09-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_planning",
            "0045_workout_categories_multi_weekday_set_targets",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="focusblock",
            name="color",
        ),
    ]
