"""
Tests for requirement 8 of the debt payment plan epic: an Expense can only
be linked, by manual user choice, to one of related_loan/related_payable/
fixed_expense_template — never more than one.

Decision 5.1: this rule applies only to the manual /transactions flow
(ExpenseSerializer.validate()), NOT to expenses auto-generated by
bulk_generate_fixed_expenses, which legitimately carry both
fixed_expense_template and related_loan/related_payable at once.
"""

from datetime import date, time
from decimal import Decimal

from django.contrib.auth.models import User
from django.test import TestCase

from accounts.models import Account
from expenses.models import Expense, FixedExpense
from expenses.serializers import ExpenseSerializer
from expenses.services import bulk_generate_fixed_expenses
from payables.models import Payable


def _make_account(name="ExclAcc"):
    return Account.objects.create(
        account_name=name,
        institution_name="NUB",
        account_type="CC",
        is_active=True,
    )


def _make_payable(value="300.00"):
    return Payable.objects.create(
        description="Conta a pagar",
        value=Decimal(value),
        date=date.today(),
        category="others",
        status="active",
    )


class ExpenseLinkExclusivitySerializerTest(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="excltest",
            email="excl@test.com",
            password="testpass123",
            is_superuser=True,
        )
        self.account = _make_account()
        self.payable = _make_payable()
        self.fixed_expense = FixedExpense.objects.create(
            description="Assinatura",
            default_value=Decimal("50.00"),
            category="digital signs",
            account=self.account,
            due_day=10,
            is_active=True,
        )

    def _base_payload(self, **overrides):
        payload = {
            "description": "Despesa manual",
            "value": "100.00",
            "date": str(date.today()),
            "horary": "10:00:00",
            "category": "others",
            "account": self.account.id,
            "payed": False,
        }
        payload.update(overrides)
        return payload

    def test_expense_rejects_two_simultaneous_links(self):
        payload = self._base_payload(
            related_payable=self.payable.id,
            fixed_expense_template=self.fixed_expense.id,
        )
        serializer = ExpenseSerializer(data=payload)
        self.assertFalse(serializer.is_valid())
        self.assertIn("related_loan", serializer.errors)

    def test_expense_allows_single_link(self):
        payload = self._base_payload(related_payable=self.payable.id)
        serializer = ExpenseSerializer(data=payload)
        self.assertTrue(serializer.is_valid(), serializer.errors)

    def test_expense_allows_no_link(self):
        payload = self._base_payload()
        serializer = ExpenseSerializer(data=payload)
        self.assertTrue(serializer.is_valid(), serializer.errors)

    def test_update_rejects_adding_second_link_to_existing_single_link(self):
        expense = Expense.objects.create(
            description="Já vinculada",
            value=Decimal("100.00"),
            date=date.today(),
            horary=time(10, 0),
            category="others",
            account=self.account,
            payed=False,
            related_payable=self.payable,
        )
        serializer = ExpenseSerializer(
            expense,
            data={"fixed_expense_template": self.fixed_expense.id},
            partial=True,
        )
        self.assertFalse(serializer.is_valid())
        self.assertIn("related_loan", serializer.errors)


class BulkGenerateExemptFromExclusivityTest(TestCase):
    """Auto-generated expenses from the debt-installment FixedExpense
    pipeline legitimately carry both fixed_expense_template and
    related_payable — bulk_generate_fixed_expenses bypasses the
    serializer entirely, so decision 5.1's exemption holds without any
    extra flag."""

    def setUp(self):
        self.user = User.objects.create_user(
            username="bulkexcltest",
            email="bulkexcl@test.com",
            password="testpass123",
            is_superuser=True,
        )
        self.account = _make_account()
        self.payable = _make_payable()
        self.fixed_expense = FixedExpense.objects.create(
            description="Parcela dívida",
            default_value=Decimal("100.00"),
            category="others",
            account=self.account,
            due_day=10,
            is_active=True,
            allow_value_edit=False,
            related_payable=self.payable,
        )

    def test_bulk_generate_exempt_from_exclusivity(self):
        today = date.today()
        month = f"{today.year}-{today.month:02d}"
        result = bulk_generate_fixed_expenses(
            month,
            [{"fixed_expense_id": self.fixed_expense.id, "value": 100.00}],
            self.user,
        )
        self.assertEqual(result["created_count"], 1)
        expense = result["expenses"][0]
        self.assertEqual(
            expense.fixed_expense_template_id, self.fixed_expense.id
        )
        self.assertEqual(expense.related_payable_id, self.payable.id)
