# Generated by Django 5.2.13 on 2026-04-20 11:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_deleted_by'),
        ('expenses', '0016_grupo3_novos_modelos'),
        ('members', '0006_member_email_verification'),
        ('revenues', '0006_grupo2_campos_simples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='revenues', to='expenses.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='FixedRevenueGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('month', models.CharField(help_text='Formato: YYYY-MM', max_length=7, unique=True, verbose_name='Mês')),
                ('total_generated', models.PositiveIntegerField(default=0, verbose_name='Total Gerado')),
                ('fixed_revenue_ids', models.JSONField(default=list, help_text='Lista de IDs dos templates que foram gerados', verbose_name='IDs das Receitas Fixas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerado Por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Log de Geração de Receitas Fixas',
                'verbose_name_plural': 'Logs de Geração de Receitas Fixas',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='FixedRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('default_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Padrão')),
                ('category', models.CharField(choices=[('deposit', 'Depósito'), ('award', 'Prêmio'), ('salary', 'Salário'), ('ticket', 'Vale'), ('income', 'Rendimentos'), ('refund', 'Reembolso'), ('cashback', 'Cashback'), ('transfer', 'Transferência Recebida'), ('received_loan', 'Empréstimo Recebido'), ('loan_devolution', 'Devolução de empréstimo')], max_length=200, verbose_name='Categoria')),
                ('due_day', models.PositiveIntegerField(help_text='Dia do mês em que a receita costuma ser recebida (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Recebimento')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar sem excluir', verbose_name='Ativa')),
                ('allow_value_edit', models.BooleanField(default=True, help_text='Permite ajustar o valor ao lançar a receita', verbose_name='Permitir Editar Valor')),
                ('last_generated_month', models.CharField(blank=True, help_text='Formato: YYYY-MM', max_length=7, null=True, verbose_name='Último Mês Gerado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='Conta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member', verbose_name='Membro Responsável')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Receita Fixa',
                'verbose_name_plural': 'Receitas Fixas',
                'ordering': ['due_day', 'description'],
                'indexes': [models.Index(fields=['account', 'is_active'], name='revenues_fi_account_d11dbc_idx'), models.Index(fields=['due_day', 'is_active'], name='revenues_fi_due_day_2415f8_idx')],
            },
        ),
    ]
