# Generated by Django 5.2.14 on 2026-05-14 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_deleted_by'),
        ('expenses', '0018_backfill_expense_is_initial_balance'),
        ('loans', '0005_grupo3_novos_modelos'),
        ('members', '0006_member_email_verification'),
        ('receivables', '0001_initial'),
        ('revenues', '0009_backfill_revenue_is_initial_balance'),
        ('transfers', '0008_grupo3_novos_modelos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='related_receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_revenues', to='receivables.receivable', verbose_name='Valor a Receber Relacionado'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['related_receivable'], name='revenues_re_related_de0aca_idx'),
        ),
    ]
