# Generated by Django 5.2.12 on 2026-03-27 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_deleted_by'),
        ('notifications', '0003_alter_notification_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('notification_type', models.CharField(choices=[('task_today', 'Tarefa do Dia'), ('task_overdue', 'Tarefa Atrasada'), ('payable_due_soon', 'Valor a Pagar Próximo do Vencimento'), ('payable_overdue', 'Valor a Pagar Atrasado'), ('loan_due_soon', 'Empréstimo Próximo do Vencimento'), ('loan_overdue', 'Empréstimo Atrasado'), ('bill_due_soon', 'Fatura Próxima do Vencimento'), ('bill_overdue', 'Fatura Atrasada')], max_length=30, verbose_name='Tipo')),
                ('channel', models.CharField(choices=[('in_app', 'Somente no App'), ('email', 'Somente E-mail'), ('both', 'App e E-mail')], default='in_app', max_length=10, verbose_name='Canal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='members.member', verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
                'ordering': ['notification_type'],
                'unique_together': {('owner', 'notification_type')},
            },
        ),
    ]
