#!/usr/bin/env python3
"""Regenerate lib/theme/app_palette_tokens.dart from the web index.css.

Transcribes the semantic tokens the web builds on top of each palette
(--muted, --muted-foreground, --border-subtle, --input, --star and
--category-*) so both apps stay in sync. Run from apps/mobile:

    python3 tool/gen_palette_tokens.py && dart format lib/theme
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CSS = ROOT / "apps/frontend/src/index.css"
OUT = ROOT / "apps/mobile/lib/theme/app_palette_tokens.dart"

TOKENS = {
    "muted": "muted",
    "muted-foreground": "mutedForeground",
    "border-subtle": "borderSubtle",
    "input": "input",
    "star": "star",
    "category-finance": "finance",
    "category-health": "health",
    "category-studies": "studies",
    "category-spiritual": "spiritual",
    "category-exercise": "exercise",
    "category-nutrition": "nutrition",
    "category-work": "work",
    "category-leisure": "leisure",
    "category-intellect": "intellect",
}

css = CSS.read_text()
blocks = {}
bases = {}
for m in re.finditer(r"^  (:root|\.dark)(\[data-(?:dark|light)-theme='([\w-]+)'\])? \{(.*?)^  \}",
                     css, re.S | re.M):
    base, _, variant, body = m.groups()
    key = variant or ("alucard" if base == ":root" else "dracula")
    bases[key] = base
    blocks[key] = dict(re.findall(r"--([\w-]+):\s*([\d.]+ [\d.]+% [\d.]+%)", body))

light_root = blocks["alucard"]
dark_root = {**light_root, **blocks["dracula"]}

lines = [
    "// GENERATED by tool/gen_palette_tokens.py from apps/frontend/src/index.css.",
    "// Do not edit by hand.",
    "import 'app_theme_variant.dart';",
    "",
    "final Map<String, AppPaletteTokens> kPaletteTokens = {",
]
for key, vals in blocks.items():
    inherited = light_root if bases[key] == ":root" else dark_root
    merged = {**inherited, **vals}
    lines.append(f"  '{key}': AppPaletteTokens(")
    for css_name, dart_name in TOKENS.items():
        h, s, l = merged[css_name].replace("%", "").split()
        lines.append(f"    {dart_name}: hsl({h}, {s}, {l}),")
    lines.append("  ),")
lines.append("};")
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(blocks)} palettes)")
