apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: axiom-staging
  labels:
    app.kubernetes.io/name: axiom
    app.kubernetes.io/component: api
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 39100
      targetPort: 39100
      protocol: TCP
      name: http
