from django.urls import path

from security.vault_config import (
    VaultChangePasswordView,
    VaultGenerateRecoveryKeyView,
    VaultLockView,
    VaultPreferencesView,
    VaultRecoveryUnlockView,
    VaultSetupView,
    VaultStatusView,
    VaultUnlockView,
)
from security.views import (  # noqa: E501  # Password/StoredCard/StoredBankAccount/Archive/ActivityLog/Dashboard views
    ActivityLogExportCSVView,
    ActivityLogListView,
    ArchiveDetailView,
    ArchiveDownloadView,
    ArchiveListCreateView,
    ArchiveRevealView,
    HibpCheckView,
    PasswordCopyView,
    PasswordDetailView,
    PasswordFavoriteToggleView,
    PasswordGenerateView,
    PasswordHistoryListView,
    PasswordImportConfirmView,
    PasswordImportPreviewView,
    PasswordListCreateView,
    PasswordRevealView,
    RedeemShareTokenView,
    RevokeShareTokenView,
    SecurityDashboardStatsView,
    ShareTokenListCreateView,
    StoredAccountShareTokenView,
    StoredBankAccountCopyView,
    StoredBankAccountDetailView,
    StoredBankAccountListCreateView,
    StoredBankAccountRevealView,
    StoredCardShareTokenView,
    StoredCreditCardCopyView,
    StoredCreditCardDetailView,
    StoredCreditCardListCreateView,
    StoredCreditCardRevealView,
    TOTPVerifyView,
    VaultAlertConfigView,
    VaultExportZipView,
    VaultHealthHistoryView,
    VaultHealthReportView,
)

urlpatterns = [
    # Vault config (senha mestre)
    path(
        "vault/export/", VaultExportZipView.as_view(), name="vault-export-zip"
    ),
    path("vault/status/", VaultStatusView.as_view(), name="vault-status"),
    path("vault/setup/", VaultSetupView.as_view(), name="vault-setup"),
    path("vault/unlock/", VaultUnlockView.as_view(), name="vault-unlock"),
    path("vault/lock/", VaultLockView.as_view(), name="vault-lock"),
    path(
        "vault/change-master-password/",
        VaultChangePasswordView.as_view(),
        name="vault-change-password",
    ),
    path(
        "vault/preferences/",
        VaultPreferencesView.as_view(),
        name="vault-preferences",
    ),
    path(
        "vault/recovery-key/generate/",
        VaultGenerateRecoveryKeyView.as_view(),
        name="vault-recovery-key-generate",
    ),
    path(
        "vault/recovery-unlock/",
        VaultRecoveryUnlockView.as_view(),
        name="vault-recovery-unlock",
    ),
    # Dashboard
    path(
        "dashboard/stats/",
        SecurityDashboardStatsView.as_view(),
        name="security-dashboard-stats",
    ),
    # Passwords
    path(
        "passwords/",
        PasswordListCreateView.as_view(),
        name="password-list-create",
    ),
    path(
        "passwords/generate/",
        PasswordGenerateView.as_view(),
        name="password-generate",
    ),
    path(
        "passwords/health/",
        VaultHealthReportView.as_view(),
        name="password-health-report",
    ),
    path(
        "passwords/import/preview/",
        PasswordImportPreviewView.as_view(),
        name="password-import-preview",
    ),
    path(
        "passwords/import/confirm/",
        PasswordImportConfirmView.as_view(),
        name="password-import-confirm",
    ),
    path(
        "passwords/<int:pk>/",
        PasswordDetailView.as_view(),
        name="password-detail",
    ),
    path(
        "passwords/<int:pk>/reveal/",
        PasswordRevealView.as_view(),
        name="password-reveal",
    ),
    path(
        "passwords/<int:pk>/copy/",
        PasswordCopyView.as_view(),
        name="password-copy",
    ),
    path(
        "passwords/<int:pk>/favorite/",
        PasswordFavoriteToggleView.as_view(),
        name="password-favorite-toggle",
    ),
    # Stored Credit Cards
    path(
        "stored-cards/",
        StoredCreditCardListCreateView.as_view(),
        name="stored-card-list-create",
    ),
    path(
        "stored-cards/<int:pk>/",
        StoredCreditCardDetailView.as_view(),
        name="stored-card-detail",
    ),
    path(
        "stored-cards/<int:pk>/reveal/",
        StoredCreditCardRevealView.as_view(),
        name="stored-card-reveal",
    ),
    path(
        "stored-cards/<int:pk>/copy/",
        StoredCreditCardCopyView.as_view(),
        name="stored-card-copy",
    ),
    # Stored Bank Accounts
    path(
        "stored-accounts/",
        StoredBankAccountListCreateView.as_view(),
        name="stored-account-list-create",
    ),
    path(
        "stored-accounts/<int:pk>/",
        StoredBankAccountDetailView.as_view(),
        name="stored-account-detail",
    ),
    path(
        "stored-accounts/<int:pk>/reveal/",
        StoredBankAccountRevealView.as_view(),
        name="stored-account-reveal",
    ),
    path(
        "stored-accounts/<int:pk>/copy/",
        StoredBankAccountCopyView.as_view(),
        name="stored-account-copy",
    ),
    # Archives
    path(
        "archives/",
        ArchiveListCreateView.as_view(),
        name="archive-list-create",
    ),
    path(
        "archives/<int:pk>/",
        ArchiveDetailView.as_view(),
        name="archive-detail",
    ),
    path(
        "archives/<int:pk>/reveal/",
        ArchiveRevealView.as_view(),
        name="archive-reveal",
    ),
    path(
        "archives/<int:pk>/download/",
        ArchiveDownloadView.as_view(),
        name="archive-download",
    ),
    # Activity Logs
    path(
        "activity-logs/",
        ActivityLogListView.as_view(),
        name="activity-log-list",
    ),
    path(
        "activity-logs/export/",
        ActivityLogExportCSVView.as_view(),
        name="activity-log-export",
    ),
    # Credential Share Tokens
    path(
        "passwords/<int:pk>/share-tokens/",
        ShareTokenListCreateView.as_view(),
        name="password-share-token-list-create",
    ),
    path(
        "stored-credit-cards/<int:pk>/share-tokens/",
        StoredCardShareTokenView.as_view(),
        name="stored-card-share-token-list-create",
    ),
    path(
        "stored-bank-accounts/<int:pk>/share-tokens/",
        StoredAccountShareTokenView.as_view(),
        name="stored-account-share-token-list-create",
    ),
    path(
        "share-tokens/<int:token_id>/revoke/",
        RevokeShareTokenView.as_view(),
        name="share-token-revoke",
    ),
    # Public endpoint — no authentication required
    path(
        "share/<uuid:token>/",
        RedeemShareTokenView.as_view(),
        name="share-token-redeem",
    ),
    # HIBP (HaveIBeenPwned) check — k-anonymity proxy
    path(
        "hibp-check/",
        HibpCheckView.as_view(),
        name="hibp-check",
    ),
    # Password History
    path(
        "passwords/<int:pk>/history/",
        PasswordHistoryListView.as_view(),
        name="password-history",
    ),
    # TOTP verify
    path(
        "passwords/<int:pk>/totp/verify/",
        TOTPVerifyView.as_view(),
        name="password-totp-verify",
    ),
    # Vault Health History (score evolution)
    path(
        "vault-health-history/",
        VaultHealthHistoryView.as_view(),
        name="vault-health-history",
    ),
    # Vault Alert Config
    path(
        "alert-config/",
        VaultAlertConfigView.as_view(),
        name="vault-alert-config",
    ),
]
