apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: axiom-staging
  labels:
    app.kubernetes.io/name: axiom
    app.kubernetes.io/component: minio
    environment: staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
        app.kubernetes.io/name: axiom
        app.kubernetes.io/component: minio
        environment: staging
    spec:
      serviceAccountName: sa-minio
      automountServiceAccountToken: false
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-11-07T00-52-20Z
          command:
            - minio
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: axiom-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: axiom-secrets
                  key: MINIO_ROOT_PASSWORD
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
