# Generated by Django 5.2.12 on 2026-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatemententry',
            name='match_confidence',
            field=models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa'), ('manual', 'Manual')], max_length=6, null=True, verbose_name='Confiança do Match'),
        ),
    ]
