# Generated by Django 5.2.13 on 2026-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_rename_budgets_bud_month_year_idx_budgets_bud_month_2b4c3d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='rollover_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor não utilizado do mês anterior acumulado neste orçamento.', max_digits=10, verbose_name='Saldo Rolado'),
        ),
        migrations.AddField(
            model_name='budget',
            name='rollover_enabled',
            field=models.BooleanField(default=False, help_text='Quando ativado, o saldo não utilizado do mês anterior é somado ao limite do mês atual.', verbose_name='Habilitar Rolagem de Saldo'),
        ),
    ]
