# Generated by Django 5.2.13 on 2026-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0005_alter_revenue_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='currency_code',
            field=models.CharField(default='BRL', help_text='Código ISO 4217 da moeda (ex: BRL, USD, EUR)', max_length=3, verbose_name='Moeda'),
        ),
    ]
