# Generated by Django 5.2.13 on 2026-05-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0007_grupo3_novos_modelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='is_initial_balance',
            field=models.BooleanField(default=False, help_text='Receita gerada automaticamente a partir do saldo inicial da conta', verbose_name='Saldo Inicial'),
        ),
    ]
