# Generated by Django 5.2.15 on 2026-07-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenues", "0010_revenue_related_receivable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="fixed_revenue_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template de receita fixa que gerou esta receita",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_revenues",
                to="revenues.fixedrevenue",
                verbose_name="Modelo de Receita Fixa",
            ),
        ),
    ]
