# Generated by Django 6.0.8 on 2026-08-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_deleted_by'),
        ('expenses', '0020_fixedexpense_related_loan_and_more'),
        ('loans', '0011_backfill_loan_type_missing'),
        ('members', '0007_member_activity_level'),
        ('receivables', '0001_initial'),
        ('revenues', '0011_revenue_fixed_revenue_template'),
        ('transfers', '0008_grupo3_novos_modelos'),
        ('vaults', '0009_fix_vault_yield_and_account_balances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='related_vault',
            field=models.ForeignKey(blank=True, help_text='Cofre cujo rendimento gerou esta receita (consolidada por mês)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yield_revenues', to='vaults.vault', verbose_name='Cofre Relacionado'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['related_vault'], name='revenues_re_related_96bb61_idx'),
        ),
    ]
