# Generated by Django 6.0.8 on 2026-09-28 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_add_totp_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, verbose_name="Excluído"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dracula", "dracula"),
                            ("catppuccin-mocha", "catppuccin-mocha"),
                            ("tokyo-night", "tokyo-night"),
                            ("gruvbox-dark", "gruvbox-dark"),
                            ("cyberpunk", "cyberpunk"),
                            (
                                "flat-remix-blue-darkest",
                                "flat-remix-blue-darkest",
                            ),
                            ("everforest", "everforest"),
                            ("ubuntu", "ubuntu"),
                            ("mint-dark", "mint-dark"),
                            ("alucard", "alucard"),
                            ("catppuccin-latte", "catppuccin-latte"),
                            ("rose-pine-dawn", "rose-pine-dawn"),
                            ("everforest-light", "everforest-light"),
                            ("gruvbox-light", "gruvbox-light"),
                            ("solarized-light", "solarized-light"),
                            ("nord-light", "nord-light"),
                            ("ubuntu-light", "ubuntu-light"),
                            ("mint-light", "mint-light"),
                        ],
                        max_length=32,
                        verbose_name="Tema",
                    ),
                ),
                (
                    "sync_token_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Hash do token de sync",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluído por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferência de tema",
                "verbose_name_plural": "Preferências de tema",
            },
        ),
    ]
