# Generated by Django 5.2.15 on 2026-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='fixed_expense_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='fixed_revenue_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
