# Generated by Django 5.2.13 on 2026-04-20 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_grupo3_novos_modelos'),
        ('loans', '0004_grupo2_campos_simples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payed', models.BooleanField(default=False, verbose_name='Pago')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_schedule', to='loans.loan', verbose_name='Empréstimo')),
                ('payment_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_installment_payments', to='expenses.expense', verbose_name='Despesa de Pagamento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Parcela de Empréstimo',
                'verbose_name_plural': 'Parcelas de Empréstimo',
                'ordering': ['loan', 'installment_number'],
                'indexes': [models.Index(fields=['loan', 'payed'], name='loans_loani_loan_id_80877c_idx'), models.Index(fields=['due_date'], name='loans_loani_due_dat_1afa52_idx')],
                'constraints': [models.UniqueConstraint(fields=('loan', 'installment_number'), name='unique_loan_installment_number')],
            },
        ),
    ]
