# Generated by Django 6.0.7 on 2026-08-17 16:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_populate_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='initial_payed_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Valor pago/recebido informado na criação do empréstimo, sem despesa/receita vinculada. Preenchido automaticamente e somado ao total apurado de despesas/receitas vinculadas ao recalcular payed_value.', max_digits=10, verbose_name='Valor Pago Inicial'),
        ),
    ]
