# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0004_vault_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "Visualização"),
                    ("create", "Criação"),
                    ("update", "Atualização"),
                    ("delete", "Exclusão"),
                    ("reveal", "Revelação de Senha/Credencial"),
                    ("download", "Download de Arquivo"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("failed_login", "Tentativa de Login Falha"),
                    ("other", "Outro"),
                    ("purge", "Purga de Dados (LGPD/GDPR)"),
                ],
                max_length=100,
                verbose_name="Ação",
            ),
        ),
        migrations.AddField(
            model_name="password",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="password_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Exclu\u00eddo por",
            ),
        ),
        migrations.AddField(
            model_name="storedcreditcard",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="storedcreditcard_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Exclu\u00eddo por",
            ),
        ),
        migrations.AddField(
            model_name="storedbankaccount",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="storedbankaccount_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Exclu\u00eddo por",
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archive_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Exclu\u00eddo por",
            ),
        ),
    ]
