# Generated by Django 5.2.12 on 2026-03-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_deletionrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deletionrecord',
            new_name='security_de_record__53ba9a_idx',
            old_name='security_de_record__idx',
        ),
        migrations.RenameIndex(
            model_name='deletionrecord',
            new_name='security_de_model_n_54bfce_idx',
            old_name='security_de_model_n_idx',
        ),
    ]
