# Generated by Django 5.2.13 on 2026-04-18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_rename_security_de_record__idx_security_de_record__53ba9a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='object_uuid',
            field=models.UUIDField(
                blank=True,
                null=True,
                help_text='UUID público do objeto afetado (correlaciona com a API)',
                verbose_name='UUID do Objeto',
            ),
        ),
        migrations.AddField(
            model_name='archive',
            name='is_file_encrypted',
            field=models.BooleanField(
                default=False,
                help_text='Indica se o arquivo foi criptografado com a vault_key do usuário',
                verbose_name='Arquivo Criptografado',
            ),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(
                choices=[
                    ('view', 'Visualização'),
                    ('create', 'Criação'),
                    ('update', 'Atualização'),
                    ('delete', 'Exclusão'),
                    ('reveal', 'Revelação de Senha/Credencial'),
                    ('download', 'Download de Arquivo'),
                    ('login', 'Login'),
                    ('logout', 'Logout'),
                    ('failed_login', 'Tentativa de Login Falha'),
                    ('failed_vault_unlock', 'Tentativa de Desbloqueio do Cofre Falha'),
                    ('other', 'Outro'),
                    ('purge', 'Purga de Dados (LGPD/GDPR)'),
                    ('shared_reveal', 'Acesso via Link Compartilhado'),
                ],
                max_length=100,
                verbose_name='Ação',
            ),
        ),
        migrations.AlterField(
            model_name='archive',
            name='tags',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de tags para categorização e busca',
                verbose_name='Tags',
            ),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['object_uuid'], name='security_ac_object__1850fb_idx'),
        ),
    ]
