# Generated by Django 5.2.15 on 2026-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0019_password_strength_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "Visualização"),
                    ("create", "Criação"),
                    ("update", "Atualização"),
                    ("delete", "Exclusão"),
                    ("reveal", "Revelação de Senha/Credencial"),
                    ("download", "Download de Arquivo"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("failed_login", "Tentativa de Login Falha"),
                    (
                        "failed_vault_unlock",
                        "Tentativa de Desbloqueio do Cofre Falha",
                    ),
                    ("other", "Outro"),
                    ("purge", "Purga de Dados (LGPD/GDPR)"),
                    ("shared_reveal", "Acesso via Link Compartilhado"),
                    ("copy", "Cópia para Área de Transferência"),
                ],
                max_length=100,
                verbose_name="Ação",
            ),
        ),
    ]
