# Generated by Django 6.0.8 on 2026-08-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0004_grupo3_novos_modelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='installments',
            field=models.PositiveIntegerField(default=1, verbose_name='Parcelas'),
        ),
        migrations.AddField(
            model_name='payable',
            name='is_cumulative',
            field=models.BooleanField(default=False, verbose_name='Dívida cumulativa'),
        ),
        migrations.AddField(
            model_name='payable',
            name='payment_frequency',
            field=models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Frequência de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payableinstallment',
            name='payable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_schedule', to='payables.payable', verbose_name='Valor a Pagar'),
        ),
    ]
