# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expense_related_payable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Exclu\u00eddo por'),
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixedexpense_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Exclu\u00eddo por'),
        ),
        migrations.AddField(
            model_name='fixedexpensegenerationlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixedexpensegenerationlog_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Exclu\u00eddo por'),
        ),
    ]
