# Generated by Django 5.2.11 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0013_categorizationrule_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorizationrule",
            name="priority",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Menor valor = maior prioridade.",
                verbose_name="Prioridade",
            ),
        ),
    ]
