# Generated by Django 5.2.13 on 2026-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_alter_categorizationrule_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency_code',
            field=models.CharField(default='BRL', help_text='Código ISO 4217 da moeda (ex: BRL, USD, EUR)', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='horary',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
