# Generated by Django 5.2.15 on 2026-06-16 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_backfill_expense_is_initial_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('logic', models.CharField(choices=[('all', 'Todas as condições (AND)'), ('any', 'Qualquer condição (OR)')], default='all', max_length=10, verbose_name='Lógica das condições')),
                ('conditions', models.JSONField(default=list, help_text='Lista de objetos {field, operator, value}', verbose_name='Condições (SE)')),
                ('actions', models.JSONField(default=list, help_text='Lista de objetos {type, value}', verbose_name='Ações (ENTÃO)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Menor valor = maior prioridade.', verbose_name='Prioridade')),
                ('apply_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Aplicações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Regra de Automação',
                'verbose_name_plural': 'Regras de Automação',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('actions_applied', models.JSONField(default=list, verbose_name='Ações aplicadas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='expenses.expense', verbose_name='Despesa')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='expenses.automationrule', verbose_name='Regra')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Log de Automação',
                'verbose_name_plural': 'Logs de Automação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['owner', 'is_active'], name='expenses_au_owner_i_70977d_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['priority'], name='expenses_au_priorit_684ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrulelog',
            index=models.Index(fields=['rule', 'created_at'], name='expenses_au_rule_id_0bd219_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrulelog',
            index=models.Index(fields=['expense'], name='expenses_au_expense_8541b9_idx'),
        ),
    ]
