// Categorias canônicas de despesas (sem duplicação - exatamente as do backend)
export const EXPENSE_CATEGORIES_CANONICAL = [
  { key: 'food and drink', label: 'Comida e Bebida', emoji: '🍽️' },
  { key: 'bills and services', label: 'Contas e Serviços', emoji: '📄' },
  { key: 'electronics', label: 'Eletrônicos', emoji: '📱' },
  { key: 'family and friends', label: 'Amizades e Família', emoji: '👨‍👩‍👧' },
  { key: 'pets', label: 'Animais de Estimação', emoji: '🐾' },
  { key: 'digital signs', label: 'Assinaturas Digitais', emoji: '📺' },
  { key: 'house', label: 'Casa', emoji: '🏠' },
  { key: 'purchases', label: 'Compras', emoji: '🛍️' },
  { key: 'donate', label: 'Doações', emoji: '💝' },
  { key: 'education', label: 'Educação', emoji: '📚' },
  { key: 'loans', label: 'Empréstimos', emoji: '🤝' },
  { key: 'entertainment', label: 'Entretenimento', emoji: '🎭' },
  { key: 'taxes', label: 'Impostos', emoji: '🏛️' },
  { key: 'investments', label: 'Investimentos', emoji: '📈' },
  { key: 'others', label: 'Outros', emoji: '📦' },
  { key: 'vestuary', label: 'Roupas', emoji: '👕' },
  { key: 'health and care', label: 'Saúde e Cuidados Pessoais', emoji: '❤️‍🩹' },
  { key: 'professional services', label: 'Serviços Profissionais', emoji: '💼' },
  { key: 'supermarket', label: 'Supermercado', emoji: '🛒' },
  { key: 'rates', label: 'Taxas', emoji: '💸' },
  { key: 'transport', label: 'Transporte', emoji: '🚗' },
  { key: 'travels', label: 'Viagens', emoji: '✈️' },
] as const;

export const REVENUE_CATEGORIES_CANONICAL = [
  { key: 'deposit', label: 'Depósito', emoji: '🏦' },
  { key: 'award', label: 'Prêmio', emoji: '🏆' },
  { key: 'salary', label: 'Salário', emoji: '💰' },
  { key: 'ticket', label: 'Vale', emoji: '🎫' },
  { key: 'income', label: 'Rendimentos', emoji: '📊' },
  { key: 'refund', label: 'Reembolso', emoji: '🔄' },
  { key: 'cashback', label: 'Cashback', emoji: '💳' },
  { key: 'transfer', label: 'Transferência Recebida', emoji: '➡️' },
  { key: 'received_loan', label: 'Empréstimo Recebido', emoji: '🤝' },
  { key: 'loan_devolution', label: 'Devolução de Empréstimo', emoji: '↩️' },
] as const;
