# Generated by Django 6.0.8 on 2026-09-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaults", "0012_fix_leaked_vault_yield_edit_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="vault",
            name="yield_index_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual do índice aplicado (ex: 120.00 = 120% do CDI)",
                max_digits=6,
                null=True,
                verbose_name="Percentual do Índice",
            ),
        ),
        migrations.AddField(
            model_name="vault",
            name="yield_index_type",
            field=models.CharField(
                choices=[
                    ("none", "Nenhum (taxa manual)"),
                    ("cdi", "CDI"),
                    ("selic", "SELIC"),
                ],
                default="none",
                help_text="Índice de referência real (CDI/SELIC) usado para recalcular annual_yield_rate automaticamente. 'Nenhum' mantém a taxa manual.",
                max_length=10,
                verbose_name="Índice de Rendimento",
            ),
        ),
    ]
