# Generated by Django 5.2.14 on 2026-05-18 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='webhooks_we_webhook_322278_idx',
            old_name='webhooks_we_webhook_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='webhooks_we_event_88a715_idx',
            old_name='webhooks_we_event_created_idx',
        ),
        migrations.AlterField(
            model_name='webhook',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='events',
            field=models.JSONField(default=list, help_text='Lista de eventos que disparam este webhook', verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(help_text='Assina o payload via HMAC-SHA256 (header X-Axiom-Signature)', max_length=128, verbose_name='Secret'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
