apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs-pvc
  namespace: axiom
spec:
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-static-pvc
  namespace: axiom
spec:
  resources:
    requests:
      storage: 200Mi
