apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
  namespace: axiom
spec:
  commonName: minio-service.axiom-staging.svc.cluster.local
  dnsNames:
    - minio-service
    - minio-service.axiom-staging
    - minio-service.axiom-staging.svc
    - minio-service.axiom-staging.svc.cluster.local
