apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: axiom
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: axiom
spec:
  resources:
    requests:
      storage: 2Gi
