apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-api-restart-ollama
  namespace: axiom
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["api", "frontend"]
    verbs: ["get", "patch"]
