# Generated by Django 6.0.8 on 2026-08-21 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_deleted_by'),
        ('credit_cards', '0008_alter_creditcard_deleted_by_and_more'),
        ('expenses', '0019_automationrule_automationrulelog'),
        ('loans', '0011_backfill_loan_type_missing'),
        ('members', '0007_member_activity_level'),
        ('payables', '0005_payable_installments_payable_is_cumulative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpense',
            name='related_loan',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando esta despesa fixa é a parcela de um plano de pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_expense_templates', to='loans.loan', verbose_name='Empréstimo Vinculado'),
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='related_payable',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando esta despesa fixa é a parcela de um plano de pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_expense_templates', to='payables.payable', verbose_name='Conta a Pagar Vinculada'),
        ),
        migrations.AddIndex(
            model_name='fixedexpense',
            index=models.Index(fields=['related_loan', 'is_active'], name='expenses_fi_related_858862_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedexpense',
            index=models.Index(fields=['related_payable', 'is_active'], name='expenses_fi_related_daaf6f_idx'),
        ),
    ]
