# Generated by Django 6.0.8 on 2026-09-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0020_fixedexpense_related_loan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixedexpense",
            name="payment_method",
        ),
    ]
