apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-media-pvc
  namespace: mindledger-staging
  labels:
    app.kubernetes.io/name: mindledger
    app.kubernetes.io/component: api
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs-pvc
  namespace: mindledger-staging
  labels:
    app.kubernetes.io/name: mindledger
    app.kubernetes.io/component: api
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-static-pvc
  namespace: mindledger-staging
  labels:
    app.kubernetes.io/name: mindledger
    app.kubernetes.io/component: api
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
