# Generated by Django 5.2.13 on 2026-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
