# Generated by Django 5.2.14 on 2026-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('borrowed', 'Empréstimo Tomado'), ('lent', 'Empréstimo Realizado')], max_length=10, null=True, verbose_name='Tipo de Empréstimo'),
        ),
    ]
