# Generated by Django 5.2.11 on 2026-03-06 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0012_expense_auto_categorized_categorizationrule"),
        ("vaults", "0005_vault_recurring_contribution"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="vaultrecurringcontribution",
            new_name="vaults_vaul_vault_i_ce8652_idx",
            old_name="vaults_vrc_vault_active_idx",
        ),
        migrations.RenameIndex(
            model_name="vaultrecurringcontribution",
            new_name="vaults_vaul_is_acti_b904e3_idx",
            old_name="vaults_vrc_active_del_idx",
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor a ser depositado mensalmente",
                max_digits=15,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="day_of_month",
            field=models.PositiveIntegerField(
                help_text="Dia do mês em que o depósito será realizado (1-31)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Dia do Mês",
            ),
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="description",
            field=models.CharField(
                help_text="Descrição da contribuição (ex: Poupança mensal)",
                max_length=200,
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Mês até o qual as contribuições serão geradas (opcional)",
                null=True,
                verbose_name="Data de Término",
            ),
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="fixed_expense",
            field=models.OneToOneField(
                blank=True,
                help_text="Template de despesa fixa gerado automaticamente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vault_contribution",
                to="expenses.fixedexpense",
                verbose_name="Despesa Fixa Associada",
            ),
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque para suspender sem excluir",
                verbose_name="Ativa",
            ),
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="last_generated_month",
            field=models.CharField(
                blank=True,
                help_text="Formato: YYYY-MM",
                max_length=7,
                null=True,
                verbose_name="Último Mês Gerado",
            ),
        ),
        migrations.AlterField(
            model_name="vaultrecurringcontribution",
            name="start_date",
            field=models.DateField(
                help_text="Mês a partir do qual as contribuições serão geradas",
                verbose_name="Data de Início",
            ),
        ),
        migrations.AlterField(
            model_name="vaulttransaction",
            name="recurring_contribution",
            field=models.ForeignKey(
                blank=True,
                help_text="Contribuição recorrente que gerou esta transação",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_transactions",
                to="vaults.vaultrecurringcontribution",
                verbose_name="Contribuição Recorrente",
            ),
        ),
    ]
