# Generated by Django 5.2.12 on 2026-03-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_deleted_by'),
        ('vaults', '0006_rename_vaults_vrc_vault_active_idx_vaults_vaul_vault_i_ce8652_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='linked_account',
            field=models.ForeignKey(blank=True, help_text='Conta usada para filtrar transações ao calcular progresso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_goals', to='accounts.account', verbose_name='Conta Vinculada'),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='linked_expense_category',
            field=models.CharField(blank=True, help_text='Categoria de despesa usada para medir progresso (para metas de redução de despesas)', max_length=200, null=True, verbose_name='Categoria de Despesa Vinculada'),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='category',
            field=models.CharField(choices=[('savings', 'Poupança'), ('investment', 'Investimento'), ('emergency', 'Reserva de Emergência'), ('travel', 'Viagem'), ('education', 'Educação'), ('property', 'Imóvel'), ('vehicle', 'Veículo'), ('retirement', 'Aposentadoria'), ('health', 'Saúde'), ('reduce_expenses', 'Reduzir Despesas'), ('increase_revenue', 'Aumentar Receitas'), ('other', 'Outro')], default='savings', max_length=50, verbose_name='Categoria'),
        ),
    ]
