# Generated by Django 5.2.13 on 2026-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_alter_transfer_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='currency_code',
            field=models.CharField(default='BRL', help_text='Código ISO 4217 da moeda (ex: BRL, USD, EUR)', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
