# Generated by Django 5.2.13 on 2026-04-20 11:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_deleted_by'),
        ('transfers', '0007_grupo2_campos_simples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedTransferGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('month', models.CharField(help_text='Formato: YYYY-MM', max_length=7, unique=True, verbose_name='Mês')),
                ('total_generated', models.PositiveIntegerField(default=0, verbose_name='Total Gerado')),
                ('fixed_transfer_ids', models.JSONField(default=list, verbose_name='IDs das Transferências Fixas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerado Por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Log de Geração de Transferências Fixas',
                'verbose_name_plural': 'Logs de Geração de Transferências Fixas',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='FixedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('category', models.CharField(choices=[('doc', 'DOC'), ('ted', 'TED'), ('pix', 'PIX')], max_length=20, verbose_name='Tipo')),
                ('due_day', models.PositiveIntegerField(help_text='Dia do mês em que a transferência deve ocorrer (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Execução')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa')),
                ('last_generated_month', models.CharField(blank=True, help_text='Formato: YYYY-MM', max_length=7, null=True, verbose_name='Último Mês Gerado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('destiny_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_transfer_destinations', to='accounts.account', verbose_name='Conta de Destino')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_transfer_origins', to='accounts.account', verbose_name='Conta de Origem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Transferência Fixa',
                'verbose_name_plural': 'Transferências Fixas',
                'ordering': ['due_day', 'description'],
                'indexes': [models.Index(fields=['is_active', 'due_day'], name='transfers_f_is_acti_703c29_idx')],
            },
        ),
    ]
