from django.urls import path

from personal_planning.views import (  # noqa: E501  # Dashboard/RoutineTasks/Goals/Reflections/Instances; Wellness Center
    AIMenuPlanGenerationView,
    AIRoutineSuggestionView,
    AIWorkoutPlanGenerationView,
    BodyMetricListCreateView,
    BodyMetricRetrieveUpdateDestroyView,
    ChallengeListCreateView,
    ChallengeRetrieveUpdateDestroyView,
    CrisisImpulseLogDetailView,
    CrisisImpulseLogListCreateView,
    CrisisImpulseResolveView,
    DailyCaloricSummaryView,
    DailyReflectionDetailView,
    DailyReflectionListCreateView,
    EmotionalCheckinDetailView,
    EmotionalCheckinListCreateView,
    ExerciseDatasetEntryListView,
    ExerciseDatasetGifStreamView,
    ExerciseDatasetThumbnailStreamView,
    ExerciseGifStreamView,
    ExerciseListCreateView,
    ExerciseRetrieveUpdateDestroyView,
    ExerciseThumbnailStreamView,
    ExportGoalsView,
    ExportMealLogsView,
    ExportReflectionsView,
    ExportWorkoutSessionsView,
    FoodListCreateView,
    FoodRetrieveUpdateDestroyView,
    GamificationProfileView,
    GoalDetailView,
    GoalListCreateView,
    GoalRecalculateView,
    GoalRegisterFailureView,
    GoalRestartView,
    InstancesForDateView,
    MealLogListCreateView,
    MealLogRetrieveUpdateDestroyView,
    MealTypeListCreateView,
    MealTypeRetrieveUpdateDestroyView,
    MenuOptionIngredientListCreateView,
    MenuOptionIngredientRetrieveUpdateDestroyView,
    MenuOptionListCreateView,
    MenuOptionRetrieveUpdateDestroyView,
    PersonalPlanningAnalyticsView,
    PersonalPlanningDashboardStatsView,
    RoutineTaskDetailView,
    RoutineTaskHeatmapView,
    RoutineTaskListCreateView,
    RoutineTemplateImportView,
    RoutineTemplateListView,
    SelfEsteemAssessmentDetailView,
    SelfEsteemAssessmentListCreateView,
    TaskInstanceBulkUpdateView,
    TaskInstanceDetailView,
    TaskInstanceListCreateView,
    TaskInstanceStatusUpdateView,
    UserRoutineTemplateDetailView,
    UserRoutineTemplateImportView,
    UserRoutineTemplateListCreateView,
    WellnessDashboardView,
    WellnessInterventionCompletionDetailView,
    WellnessInterventionCompletionListCreateView,
    WellnessInterventionListView,
    WellnessWeeklyReportGenerateView,
    WellnessWeeklyReportListView,
    WorkoutDayListCreateView,
    WorkoutDayRetrieveUpdateDestroyView,
    WorkoutExerciseListCreateView,
    WorkoutExerciseRetrieveUpdateDestroyView,
    WorkoutPlanListCreateView,
    WorkoutPlanRetrieveUpdateDestroyView,
    WorkoutSessionExerciseListCreateView,
    WorkoutSessionExerciseRetrieveUpdateDestroyView,
    WorkoutSessionListCreateView,
    WorkoutSessionRetrieveUpdateDestroyView,
    WorkoutSessionSetListCreateView,
    WorkoutSessionSetRetrieveUpdateDestroyView,
)

urlpatterns = [
    # Dashboard
    path(
        "dashboard/stats/",
        PersonalPlanningDashboardStatsView.as_view(),
        name="personal-planning-dashboard-stats",
    ),
    # Analytics
    path(
        "analytics/",
        PersonalPlanningAnalyticsView.as_view(),
        name="personal-planning-analytics",
    ),
    # Routine Tasks
    path(
        "routine-tasks/",
        RoutineTaskListCreateView.as_view(),
        name="routine-task-list-create",
    ),
    path(
        "routine-tasks/heatmap/",
        RoutineTaskHeatmapView.as_view(),
        name="routine-task-heatmap",
    ),
    path(
        "routine-tasks/<int:pk>/",
        RoutineTaskDetailView.as_view(),
        name="routine-task-detail",
    ),
    # Routine Templates (read-only seed data)
    path(
        "routine-templates/",
        RoutineTemplateListView.as_view(),
        name="routine-template-list",
    ),
    path(
        "routine-templates/import/",
        RoutineTemplateImportView.as_view(),
        name="routine-template-import",
    ),
    # User Routine Templates (user-created)
    path(
        "user-routine-templates/",
        UserRoutineTemplateListCreateView.as_view(),
        name="user-routine-template-list-create",
    ),
    path(
        "user-routine-templates/<int:pk>/",
        UserRoutineTemplateDetailView.as_view(),
        name="user-routine-template-detail",
    ),
    path(
        "user-routine-templates/<int:pk>/import/",
        UserRoutineTemplateImportView.as_view(),
        name="user-routine-template-import",
    ),
    # Goals
    path("goals/", GoalListCreateView.as_view(), name="goal-list-create"),
    path("goals/<int:pk>/", GoalDetailView.as_view(), name="goal-detail"),
    path(
        "goals/<int:pk>/recalculate/",
        GoalRecalculateView.as_view(),
        name="goal-recalculate",
    ),
    path(
        "goals/<int:pk>/restart/",
        GoalRestartView.as_view(),
        name="goal-restart",
    ),
    path(
        "goals/<int:pk>/register-failure/",
        GoalRegisterFailureView.as_view(),
        name="goal-register-failure",
    ),
    # Daily Reflections
    path(
        "reflections/",
        DailyReflectionListCreateView.as_view(),
        name="daily-reflection-list-create",
    ),
    path(
        "reflections/<int:pk>/",
        DailyReflectionDetailView.as_view(),
        name="daily-reflection-detail",
    ),
    # Task Instances
    path(
        "instances/",
        TaskInstanceListCreateView.as_view(),
        name="task-instance-list-create",
    ),
    path(
        "instances/<int:pk>/",
        TaskInstanceDetailView.as_view(),
        name="task-instance-detail",
    ),
    path(
        "instances/for-date/",
        InstancesForDateView.as_view(),
        name="instances-for-date",
    ),
    path(
        "instances/<int:pk>/status/",
        TaskInstanceStatusUpdateView.as_view(),
        name="task-instance-status-update",
    ),
    path(
        "instances/bulk-update/",
        TaskInstanceBulkUpdateView.as_view(),
        name="task-instance-bulk-update",
    ),
    path(
        "gamification/",
        GamificationProfileView.as_view(),
        name="gamification-profile",
    ),
    # Exercise Catalog
    path(
        "exercises/",
        ExerciseListCreateView.as_view(),
        name="exercise-list-create",
    ),
    path(
        "exercises/<int:pk>/",
        ExerciseRetrieveUpdateDestroyView.as_view(),
        name="exercise-detail",
    ),
    path(
        "exercises/<int:pk>/gif/",
        ExerciseGifStreamView.as_view(),
        name="exercise-gif-stream",
    ),
    path(
        "exercises/<int:pk>/thumbnail/",
        ExerciseThumbnailStreamView.as_view(),
        name="exercise-thumbnail-stream",
    ),
    # Exercise Dataset (picker de imagens)
    path(
        "exercise-dataset/",
        ExerciseDatasetEntryListView.as_view(),
        name="exercise-dataset-list",
    ),
    path(
        "exercise-dataset/<int:pk>/gif/",
        ExerciseDatasetGifStreamView.as_view(),
        name="exercise-dataset-gif-stream",
    ),
    path(
        "exercise-dataset/<int:pk>/thumbnail/",
        ExerciseDatasetThumbnailStreamView.as_view(),
        name="exercise-dataset-thumbnail-stream",
    ),
    # Workout Plans
    path(
        "workout-plans/",
        WorkoutPlanListCreateView.as_view(),
        name="workout-plan-list-create",
    ),
    path(
        "workout-plans/<int:pk>/",
        WorkoutPlanRetrieveUpdateDestroyView.as_view(),
        name="workout-plan-detail",
    ),
    # Workout Days
    path(
        "workout-days/",
        WorkoutDayListCreateView.as_view(),
        name="workout-day-list-create",
    ),
    path(
        "workout-days/<int:pk>/",
        WorkoutDayRetrieveUpdateDestroyView.as_view(),
        name="workout-day-detail",
    ),
    # Workout Exercises
    path(
        "workout-exercises/",
        WorkoutExerciseListCreateView.as_view(),
        name="workout-exercise-list-create",
    ),
    path(
        "workout-exercises/<int:pk>/",
        WorkoutExerciseRetrieveUpdateDestroyView.as_view(),
        name="workout-exercise-detail",
    ),
    # Workout Sessions
    path(
        "workout-sessions/",
        WorkoutSessionListCreateView.as_view(),
        name="workout-session-list-create",
    ),
    path(
        "workout-sessions/<int:pk>/",
        WorkoutSessionRetrieveUpdateDestroyView.as_view(),
        name="workout-session-detail",
    ),
    # Workout Session Exercises
    path(
        "workout-session-exercises/",
        WorkoutSessionExerciseListCreateView.as_view(),
        name="workout-session-exercise-list-create",
    ),
    path(
        "workout-session-exercises/<int:pk>/",
        WorkoutSessionExerciseRetrieveUpdateDestroyView.as_view(),
        name="workout-session-exercise-detail",
    ),
    # Workout Session Sets
    path(
        "workout-session-sets/",
        WorkoutSessionSetListCreateView.as_view(),
        name="workout-session-set-list-create",
    ),
    path(
        "workout-session-sets/<int:pk>/",
        WorkoutSessionSetRetrieveUpdateDestroyView.as_view(),
        name="workout-session-set-detail",
    ),
    # Foods
    path("foods/", FoodListCreateView.as_view(), name="food-list-create"),
    path(
        "foods/<int:pk>/",
        FoodRetrieveUpdateDestroyView.as_view(),
        name="food-detail",
    ),
    # Meal Types
    path(
        "meal-types/",
        MealTypeListCreateView.as_view(),
        name="meal-type-list-create",
    ),
    path(
        "meal-types/<int:pk>/",
        MealTypeRetrieveUpdateDestroyView.as_view(),
        name="meal-type-detail",
    ),
    # Menu Options
    path(
        "menu-options/",
        MenuOptionListCreateView.as_view(),
        name="menu-option-list-create",
    ),
    path(
        "menu-options/<int:pk>/",
        MenuOptionRetrieveUpdateDestroyView.as_view(),
        name="menu-option-detail",
    ),
    # Menu Option Ingredients
    path(
        "menu-option-ingredients/",
        MenuOptionIngredientListCreateView.as_view(),
        name="menu-option-ingredient-list-create",
    ),
    path(
        "menu-option-ingredients/<int:pk>/",
        MenuOptionIngredientRetrieveUpdateDestroyView.as_view(),
        name="menu-option-ingredient-detail",
    ),
    # Meal Logs
    path(
        "meal-logs/",
        MealLogListCreateView.as_view(),
        name="meal-log-list-create",
    ),
    path(
        "meal-logs/<int:pk>/",
        MealLogRetrieveUpdateDestroyView.as_view(),
        name="meal-log-detail",
    ),
    # Export endpoints
    path(
        "workout-sessions/export/",
        ExportWorkoutSessionsView.as_view(),
        name="workout-sessions-export",
    ),
    path(
        "meal-logs/export/",
        ExportMealLogsView.as_view(),
        name="meal-logs-export",
    ),
    path(
        "reflections/export/",
        ExportReflectionsView.as_view(),
        name="reflections-export",
    ),
    path(
        "goals/export/",
        ExportGoalsView.as_view(),
        name="goals-export",
    ),
    # Challenges
    path(
        "challenges/",
        ChallengeListCreateView.as_view(),
        name="challenge-list-create",
    ),
    path(
        "challenges/<int:pk>/",
        ChallengeRetrieveUpdateDestroyView.as_view(),
        name="challenge-detail",
    ),
    # Body Metrics
    path(
        "body-metrics/",
        BodyMetricListCreateView.as_view(),
        name="body-metric-list-create",
    ),
    path(
        "body-metrics/<int:pk>/",
        BodyMetricRetrieveUpdateDestroyView.as_view(),
        name="body-metric-detail",
    ),
    # AI Routine Suggestion
    path(
        "ai-routine/",
        AIRoutineSuggestionView.as_view(),
        name="ai-routine-suggestion",
    ),
    # AI Workout Plan Generation
    path(
        "ai-workout-plan/",
        AIWorkoutPlanGenerationView.as_view(),
        name="ai-workout-plan-generation",
    ),
    # AI Menu Plan Generation
    path(
        "ai-menu-plan/",
        AIMenuPlanGenerationView.as_view(),
        name="ai-menu-plan-generation",
    ),
    # Daily Caloric Summary
    path(
        "daily-caloric-summary/",
        DailyCaloricSummaryView.as_view(),
        name="daily-caloric-summary",
    ),
    # ── Wellness Center ────────────────────────────────────────────
    path(
        "wellness/dashboard/",
        WellnessDashboardView.as_view(),
        name="wellness-dashboard",
    ),
    path(
        "wellness/self-esteem/",
        SelfEsteemAssessmentListCreateView.as_view(),
        name="self-esteem-list-create",
    ),
    path(
        "wellness/self-esteem/<int:pk>/",
        SelfEsteemAssessmentDetailView.as_view(),
        name="self-esteem-detail",
    ),
    path(
        "wellness/checkins/",
        EmotionalCheckinListCreateView.as_view(),
        name="emotional-checkin-list-create",
    ),
    path(
        "wellness/checkins/<int:pk>/",
        EmotionalCheckinDetailView.as_view(),
        name="emotional-checkin-detail",
    ),
    path(
        "wellness/crisis/",
        CrisisImpulseLogListCreateView.as_view(),
        name="crisis-impulse-list-create",
    ),
    path(
        "wellness/crisis/<int:pk>/",
        CrisisImpulseLogDetailView.as_view(),
        name="crisis-impulse-detail",
    ),
    path(
        "wellness/crisis/<int:pk>/resolve/",
        CrisisImpulseResolveView.as_view(),
        name="crisis-impulse-resolve",
    ),
    path(
        "wellness/interventions/",
        WellnessInterventionListView.as_view(),
        name="wellness-intervention-list",
    ),
    path(
        "wellness/intervention-completions/",
        WellnessInterventionCompletionListCreateView.as_view(),
        name="wellness-intervention-completion-list-create",
    ),
    path(
        "wellness/intervention-completions/<int:pk>/",
        WellnessInterventionCompletionDetailView.as_view(),
        name="wellness-intervention-completion-detail",
    ),
    path(
        "wellness/weekly-reports/",
        WellnessWeeklyReportListView.as_view(),
        name="wellness-weekly-report-list",
    ),
    path(
        "wellness/weekly-reports/generate/",
        WellnessWeeklyReportGenerateView.as_view(),
        name="wellness-weekly-report-generate",
    ),
]
