# Generated by Django 5.2.13 on 2026-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_archive_tags_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='description_key',
            field=models.CharField(blank=True, help_text='Chave i18n para descrição traduzível (ex: password.create)', max_length=100, null=True, verbose_name='Chave de descrição'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='description_params',
            field=models.JSONField(blank=True, help_text='Parâmetros dinâmicos para interpolação da chave de descrição', null=True, verbose_name='Parâmetros da descrição'),
        ),
    ]
