# Generated by Django 5.2.14 on 2026-05-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_credentialsharetoken_allowed_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultconfig',
            name='recovery_encrypted_vault_key',
            field=models.TextField(blank=True, null=True, verbose_name='Chave do Cofre (cifrada com chave de recuperação)'),
        ),
        migrations.AddField(
            model_name='vaultconfig',
            name='recovery_key_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash da Chave de Recuperação (SHA-256)'),
        ),
    ]
