# Generated by Django 5.2.15 on 2026-06-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0021_add_institution_code_to_stored_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
        migrations.AddField(
            model_name='storedbankaccount',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
        migrations.AddField(
            model_name='storedcreditcard',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
    ]
