# Generated by Django 5.2.15 on 2026-06-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0022_add_is_favorite_to_stored_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultalertconfig',
            name='alert_on_card_reveal',
            field=models.BooleanField(default=False, verbose_name='Alertar ao revelar cartão bancário'),
        ),
        migrations.AddField(
            model_name='vaultalertconfig',
            name='alert_on_excessive_reveals',
            field=models.BooleanField(default=True, verbose_name='Alertar em volume excessivo de revelações'),
        ),
        migrations.AddField(
            model_name='vaultalertconfig',
            name='excessive_reveals_threshold',
            field=models.IntegerField(default=5, verbose_name='Threshold de revelações em 1 hora'),
        ),
        migrations.AddField(
            model_name='vaultalertconfig',
            name='notify_email',
            field=models.BooleanField(default=False, verbose_name='Enviar alertas por e-mail'),
        ),
    ]
